apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management:clusternet-addon:agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:clusternet-addon:agent
subjects:
  - kind: ServiceAccount
    name: clusternet-addon-sa
    namespace: {{ .AddonInstallNamespace }}
