apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:clusternet-addon:{{ .ClusterName }}
rules:
# Allow clusternet-addon agent to access the websokets server on the hub
- apiGroups: ["proxies.clusternet.io"]
  resources: ["sockets"]
  resourceNames: ["{{ .ClusterName }}"]
  verbs: ["*"]
