apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clusternet-addon
  namespace: {{ .AddonInstallNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clusternet-addon
subjects:
  - kind: ServiceAccount
    name: clusternet-addon-sa
